####################
# UseOctomap.cmake #
####################

SET(OCTOMAP_ROOT_DIR_DEBUG "${PROJECT_SOURCE_DIR}/../../octomap/install-debug" CACHE PATH "The Octomap root directory")
SET(OCTOMAP_ROOT_DIR_RELEASE "${PROJECT_SOURCE_DIR}/../../octomap/install-release" CACHE PATH "The Octomap root directory")

SET(OCTOMAP_INCLUDE_DIR "${OCTOMAP_ROOT_DIR_RELEASE}/include")

INCLUDE_DIRECTORIES(${OCTOMAP_INCLUDE_DIR})

SET(OCTOMAP_LIB_DIR_DEBUG "${OCTOMAP_ROOT_DIR_DEBUG}/lib")
SET(OCTOMAP_LIB_DIR_RELEASE "${OCTOMAP_ROOT_DIR_RELEASE}/lib")

# FIXME: Make and use separate debug libraries.
FIND_LIBRARY(OCTOMAP_LIBRARY_DEBUG octomap HINTS "${OCTOMAP_LIB_DIR_DEBUG}")
FIND_LIBRARY(OCTOMATH_LIBRARY_DEBUG octomath HINTS "${OCTOMAP_LIB_DIR_DEBUG}")

FIND_LIBRARY(OCTOMAP_LIBRARY_RELEASE octomap HINTS "${OCTOMAP_LIB_DIR_RELEASE}")
FIND_LIBRARY(OCTOMATH_LIBRARY_RELEASE octomath HINTS "${OCTOMAP_LIB_DIR_RELEASE}")

SET(OCTOMAP_LIBRARY debug ${OCTOMAP_LIBRARY_DEBUG} optimized ${OCTOMAP_LIBRARY_RELEASE})
SET(OCTOMATH_LIBRARY debug ${OCTOMATH_LIBRARY_DEBUG} optimized ${OCTOMATH_LIBRARY_RELEASE})

SET(OCTOMAP_LIBRARIES
${OCTOMAP_LIBRARY}
${OCTOMATH_LIBRARY}
)
